@FinSim_HostAddress = http://localhost:5209
@user = f0000000-0000-0000-0000-000000000001
@thyao = 11111111-1111-1111-1111-111111111111
@asels = 22222222-2222-2222-2222-222222222222
@hekts = dddddddd-dddd-dddd-dddd-dddddddddddd

### T0 - Hisse listesi (13 hisse, HEKTS inactive) ///////////////////////////////////////////////////
GET {{FinSim_HostAddress}}/api/instruments

### T1 - Baslangic bakiyesi: 100000 free, 0 locked ///////////////////////////////////////////////////
GET {{FinSim_HostAddress}}/api/users/{{user}}/balance

### T2 - Sembol ile sorgu ///////////////////////////////////////////////////////////////////////////
GET {{FinSim_HostAddress}}/api/instruments/THYAO

### T3 - Adet 0 -> 400 //////////////////////////////////////////////////////////////////////////////
POST {{FinSim_HostAddress}}/api/order/market
Content-Type: application/json

{ "userId": "{{user}}", "instrumentId": "{{thyao}}", "direction": "Buy", "quantity": 0 }

### T4 - Negatif adet -> 400 ////////////////////////////////////////////////////////////////////////
POST {{FinSim_HostAddress}}/api/order/limit
Content-Type: application/json

{ "userId": "{{user}}", "instrumentId": "{{thyao}}", "direction": "Buy", "quantity": -5, "price": 100 }

### T5 - Fiyat 0 -> 400 !!!400 VERMEDI /////////////////////////////////////////////////////////////////////////////
POST {{FinSim_HostAddress}}/api/order/limit
Content-Type: application/json

{ "userId": "{{user}}", "instrumentId": "{{thyao}}", "direction": "Buy", "quantity": 10, "price": 0 }

### T6 - Inaktif hisse HEKTS -> 400 /////////////////////////////////////////////////////////////////
POST {{FinSim_HostAddress}}/api/order/market
Content-Type: application/json

{ "userId": "{{user}}", "instrumentId": "{{hekts}}", "direction": "Buy", "quantity": 5 }

### T7 - Yetersiz bakiye (Senaryo 2) -> 400 /////////////////////////////////////////////////////////
POST {{FinSim_HostAddress}}/api/order/limit
Content-Type: application/json

{ "userId": "{{user}}", "instrumentId": "{{thyao}}", "direction": "Buy", "quantity": 100000, "price": 100 }

### T8 - Elinde olmayan hisseyi sat -> 400 //////////////////////////////////////////////////////////
POST {{FinSim_HostAddress}}/api/order/market
Content-Type: application/json

{ "userId": "{{user}}", "instrumentId": "{{asels}}", "direction": "Sell", "quantity": 5 }

### T9 - Bakiye hala 100000 / 0 olmali //////////////////////////////////////////////////////////////
GET {{FinSim_HostAddress}}/api/users/{{user}}/balance

### T10 - Dolmayacak limit alis (30 TL), ID'yi not al ///////////////////////////////////////////////
POST {{FinSim_HostAddress}}/api/order/limit 78468ed9-740c-443d-acb8-a54e4fe1aff0
Content-Type: application/json

{ "userId": "{{user}}", "instrumentId": "{{thyao}}", "direction": "Buy", "quantity": 10, "price": 30.00 }

### T11 - locked = 300, free = 99700 ////////////////////////////////////////////////////////////////
GET {{FinSim_HostAddress}}/api/users/{{user}}/balance

### T12 - Iptal (ORDER_ID'yi T10'dan yapistir) //////////////////////////////////////////////////////
POST {{FinSim_HostAddress}}/api/order/78468ed9-740c-443d-acb8-a54e4fe1aff0/cancel

### T13 - locked = 0, free = 100000 (tam iade) //////////////////////////////////////////////////////
GET {{FinSim_HostAddress}}/api/users/{{user}}/balance

### T14 - Ikinci kez iptal -> 400 ///////////////////////////////////////////////////////////////////
POST {{FinSim_HostAddress}}/api/order/78468ed9-740c-443d-acb8-a54e4fe1aff0/cancel

### T15 - 10 lot market alis ///////////////////////////////////////////////////////////////////////
POST {{FinSim_HostAddress}}/api/order/market
Content-Type: application/json

{ "userId": "{{user}}", "instrumentId": "{{thyao}}", "direction": "Buy", "quantity": 10 }

### T16 - Biraz bekle, 10 lot daha al (AverageCost degismeli) ///////////////////////////////////////
POST {{FinSim_HostAddress}}/api/order/market
Content-Type: application/json

{ "userId": "{{user}}", "instrumentId": "{{thyao}}", "direction": "Buy", "quantity": 1000 }

### T17 - Market satis 5 lot (AverageCost DEGISMEMELI) //////////////////////////////////////////////
POST {{FinSim_HostAddress}}/api/order/market
Content-Type: application/json

{ "userId": "{{user}}", "instrumentId": "{{thyao}}", "direction": "Sell", "quantity": 5 }

### T18 - Yuksek fiyatli limit alis (hemen dolar) ///////////////////////////////////////////////////
POST {{FinSim_HostAddress}}/api/order/limit
Content-Type: application/json

{ "userId": "{{user}}", "instrumentId": "{{thyao}}", "direction": "Buy", "quantity": 5, "price": 500.00 }

### T19 - 5 saniye bekle, locked 0'a donmus olmali //////////////////////////////////////////////////
GET {{FinSim_HostAddress}}/api/users/{{user}}/balance

### T20 - Dusuk fiyatli limit satis (hemen dolar) ///////////////////////////////////////////////////
POST {{FinSim_HostAddress}}/api/order/limit
Content-Type: application/json

{ "userId": "{{user}}", "instrumentId": "{{thyao}}", "direction": "Sell", "quantity": 5, "price": 1.00 }

### T21 - Son durum /////////////////////////////////////////////////////////////////////////////////
GET {{FinSim_HostAddress}}/api/users/{{user}}/balance

### T22 - Portfoy /////////////////////////////////////////////////////////////////////////////////
GET {{FinSim_HostAddress}}/api/users/{{user}}/portfolio